# Generated by Django 6.0.5 on 2026-05-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_car_owners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['license_plate'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='accrual',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='parking.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parking.car', verbose_name='Автомобиль'),
        ),
    ]
