# Generated by Django 6.0.5 on 2026-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_news_created_at_news_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('alt_text', models.CharField(help_text='Кратко опишите содержание изображения для пользователей скринридеров', max_length=200, verbose_name='Альтернативный текст изображения')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Ссылка баннера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название партнёра')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип партнёра')),
                ('website', models.URLField(max_length=500, verbose_name='Сайт партнёра')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
