# Generated by Django 6.0.5 on 2026-09-15 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_banner_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='company/audio/', verbose_name='Аудиозапись о компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(blank=True, verbose_name='Текст сертификата'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='company/documents/', verbose_name='Документ для скачивания'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, verbose_name='Реквизиты компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Укажите ссылку для встраивания видео, например https://www.youtube.com/embed/...', max_length=500, verbose_name='Ссылка на видео'),
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('event', models.TextField(verbose_name='Описание события')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='parking.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Событие истории компании',
                'verbose_name_plural': 'История компании',
                'ordering': ['year', 'id'],
            },
        ),
    ]
