# Generated by Django 6.0.5 on 2026-09-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_remove_companyinfo_video_url_companyinfo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='certificate_text',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Cертификат'),
        ),
    ]
