# Generated by Django 6.0.5 on 2026-05-16 17:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_category_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма начисления'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='month',
            field=models.PositiveSmallIntegerField(help_text='1-12', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Гос. номер может содержать только заглавные буквы, цифры и дефис', regex='^[A-Z0-9\\- ]+$')], verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Формат: +375 (29) XXX-XX-XX', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +375 (29) XXX-XX-XX', regex='^\\+375 \\((25|29|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.IntegerField(help_text='Номера места от 1 до 999', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Номер места'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена за месяц'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.IntegerField(help_text='От 1 до 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
