# Generated by Django 6.0.5 on 2026-05-17 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_accrual_amount_alter_accrual_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(limit_choices_to={'is_staff': False}, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Владельцы'),
        ),
    ]
