# Generated by Django 6.0.5 on 2026-05-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_companyinfo_alter_accrual_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='main_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Главный логотип'),
        ),
    ]
