# Generated by Django 6.0.5 on 2026-09-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_companyinfo_audio_companyinfo_certificate_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='company/video/', verbose_name='Видео о компании'),
        ),
    ]
